# Generated by Django 6.0 on 2025-12-09 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WorkThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_number', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bus', 'Bus'), ('car', 'Car'), ('golf_cart', 'Golf Cart'), ('e_rickshaw', 'E-Rickshaw'), ('ambulance', 'Ambulance'), ('other', 'Other Vehicle')], max_length=20, null=True)),
                ('document_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_1_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_2_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_3_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_4_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('workcompleted', 'Work Completed'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_remark', models.TextField(blank=True, null=True)),
                ('approval_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_threads', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_threads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to=settings.AUTH_USER_MODEL)),
                ('request_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='glamth.requestcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_type', models.CharField(choices=[('initial', 'Initial Estimate'), ('delay', 'Delay Update'), ('completed', 'Completion Update')], max_length=20)),
                ('expected_end_date', models.DateField()),
                ('delay_reason', models.TextField(blank=True, help_text='Required only if progress_type is delay', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='glamth.workthread')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('system', 'System')], default='text', max_length=20)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='thread_messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_private_messages', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='glamth.workthread')),
            ],
        ),
    ]
