# Generated by Django 6.0 on 2025-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0004_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workthread',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('workcompleted', 'Work Completed'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
