# Generated by Django 6.0 on 2025-12-19 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0005_alter_workthread_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_at', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('work_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='glamth.workthread')),
            ],
        ),
    ]
