# Generated by Django 6.0 on 2026-02-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0006_reminderthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_no', models.CharField(max_length=100, unique=True)),
                ('approval_type', models.CharField(max_length=100)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_address', models.TextField()),
                ('vendor_contact', models.CharField(max_length=50)),
                ('related_person_name', models.CharField(max_length=255)),
                ('related_person_designation', models.CharField(max_length=255)),
                ('related_person_contact', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('item_received_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='glamth.workthread')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('initiator', 'Initiator'), ('recommender', 'Recommender'), ('cfo', 'CFO'), ('chancellor', 'Chancellor'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow', to='glamth.approval')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_issue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overall_status', models.CharField(default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_master', to='glamth.approval')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_no', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('transaction_by', models.CharField(max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by', models.CharField(max_length=255)),
                ('bank_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='glamth.paymentmaster')),
            ],
        ),
    ]
