# Generated by Django 6.0 on 2026-02-05 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0007_approval_approvalflow_paymentmaster_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmessage',
            name='seen_by',
        ),
        migrations.CreateModel(
            name='MessageSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to='glamth.threadmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_seen_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
