# Generated by Django 6.0 on 2026-02-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0009_threadmessage_seen_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmessage',
            name='seen_by',
        ),
        migrations.DeleteModel(
            name='MessageSeen',
        ),
    ]
