# Generated by Django 6.0 on 2026-02-05 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamth', '0010_remove_threadmessage_seen_by_delete_messageseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
